[firebaseConfig]
apiKey: "AIzaSyDb1hL8gdjVwQW5hMbF93q2IpAK-4Jap_o",
authDomain: "youth-pulse.firebaseapp.com",
projectId: "youth-pulse",
storageBucket: "youth-pulse.appspot.com",
messagingSenderId: "436189635419",
appId: "1:436189635419:web:7efb7246e64c774077f07e"
