[firebaseConfig]
apiKey = "AIzaSyBvl4W6kdXORHktlZLtLBwKuwd3eYur7VM"
authDomain = "youth-pulse-888c4.firebaseapp.com"
projectId = "youth-pulse-888c4"
storageBucket = "youth-pulse-888c4.appspot.com"
messagingSenderId = "65147586190"
appId = "1:65147586190:web:002db753c806a0065c6bdf"
databaseURL = ""
